### ISSUE TITLE
Use UIVisualEffects to create "Night mode"

### ISSUE THREAD

**Issue by acegreen** [ide/UIVisualEffects#5]
Hello,

Can you show how to use this UIVisualEffects to create a day/night mode effect? 

I'm trying to implement this on my whole view thats creating in SB, and have that day/night effect when a button is pressed.

Thanks in advance,
Ace

**Comment by ide** [comment]
You could re-render your entire view hierarchy, changing your UIBlurEffects from Light/ExtraLight to Dark. UIVisualEffects doesn't magically handle this for you. It just provides blur and vibrancy effects.

**Comment by acegreen** [comment]
Appreciate the feedback,

How do you render the whole view hierarchy. 

I was hoping you can show that, hence the issue. I actually wanted to just leave a comment but it seems github doesn't allow that

**Comment by ide** [comment]
You could blow away your entire view hierarchy and just re-add it. This might work:
```swift
let superview = viewController.view.superview
viewController.view.removeFromSuperview()
viewController.view = nil
viewController.darkMode = true  // You define this property yourself and handle it
superview.addSubview(viewController.view)
```

**Comment by acegreen** [comment]
I’m not sure if this is a good idea in my case. I create 3 cards subviews which I could need to recreate? 

I tried to just remove the blur view and re add it but that didn’t work

            // Replace blur effect
            self.blurView.removeFromSuperview()
            blureffect = UIBlurEffect(style: .Dark)
            blurView = UIVisualEffectView(effect: blureffect)
            self.view.insertSubview(blurView, atIndex: 0)

**Comment by acegreen** [comment]
Any idea regarding this?

**Comment by ide** [comment]
I'm not sure why your example doesn't work but here's not much specific to UIVisualEffects with what you want to do.
