### ISSUE TITLE
Differenct UIEffectView

### ISSUE THREAD

**Issue by szuniverse** [ide/UIVisualEffects#6]
If I set all UIVisualEffectView blur style to UIBlurEffect(style: .Light)
Its not so smooth, there is an edge..
Do you know how to solve this? I know it can be solved with one big uieffectView but I want to separate it.

Here is why I would like to do this: 
http://stackoverflow.com/questions/30584499/uivisualeffect-view-edge-to-edge-do-not-line-up

another related question: http://stackoverflow.com/questions/31496563/custom-uivisualeffectview-with-blur-is-not-the-same-as-uinavigationbat-blur-view

Here is a screenshot from your project:
![screen shot 2015-07-19 at 01 57 44](https://cloud.githubusercontent.com/assets/7426176/8763998/ba690b80-2db9-11e5-9dfa-b42c8ed0ac28.png)

**Comment by ide** [comment]
I'm not sure but believe this isn't support by Apple so you should ask them if they will build it.
