### ISSUE TITLE
Dark blur looks more like gray

### ISSUE THREAD

**Issue by agirault** [ide/UIVisualEffects#8]
Hi @ide,

I'm trying to use the Dark UIBlurEffect, but when I apply it on top of a black background, that image becomes grey and doesn't stay black. Is there a way to do "Extra Dark", or is there something I'm missing? The blur from iOS pull-down notification center looks much Darker than what the UIBlurEffect currently gives me.

**Comment by ide** [comment]
It looks like Extra Dark (and Prominent and Regular) are options: https://developer.apple.com/reference/uikit/uiblureffectstyle. Extra Dark is listed as tvOS-only but that might not actually be true. Try it and see?

**Comment by agirault** [comment]
Nope, sadly you're right, tv-os only.
